# kind: Service
# apiVersion: v1
# metadata:
#         name: my-service
# spec:
#         selector:
#                 app: MyApp
#         ports:
#         - protocol: TCP
#           port: 80
#           targetPort: 9376
apiVersion: v1
kind: Service
metadata:
        name: default-subdomain
spec:
        selector:
                name: busybox
        clusterIP: None
        ports:
        - name: foo
          port: 1234
          targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
        name: busybox1
        labels:
                name: busybox
spec:
        hostname: busybox-1
        subdomain: default-subdomain
        containers:
        - image: busybox
          command:
                - sleep
                - "3600"
          name: busybox
