apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo
    tier: backend
    track: stable
  # Required for linkerd
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080