apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # Encode: echo -n 'john.doe' | base64
  # Decode: echo 'b64 str' | base64 --decode
  username: am9obi5kb2U=
  password: c2VjcmV0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-secret-deployment
  labels:
    app: go-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-secret
  template:
    metadata:
      labels:
        app: go-secret
    spec:
      containers:
        - name: go-secret
          image: alextanhongpin/go-secret:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: foo
              mountPath: "/etc/foo"
              readOnly: true
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
      volumes:
        - name: foo
          secret:
            secretName: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: go-secret-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: go-secret
