apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  selector:
    app: green
    tier: backend
    track: canary
  # Required for linkerd
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080