apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  selector:
    matchLabels: 
      app: grpc-server
  replicas: 3
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: alextanhongpin/node-grpc-base-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: 0.0.0.0:50051