apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
spec:
  selector:
    app: echo
    tier: backend
    track: stable
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort