apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: default
spec:
  selector:
    matchLabels:
      app: echo
      tier: backend
      track: stable
  replicas: 5
  template:
    metadata:
      labels:
        app: echo
        tier: backend
        track: stable
    spec:
      containers:
      - name: echo
        image: alextanhongpin/echo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
spec:
  selector:
    app: echo
    tier: backend
    track: stable
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer