apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      tier: backend
  template:
    metadata:
      labels:
        app: server
        tier: backend
    spec:
      containers:
        - name: server
          image: alextanhongpin/server:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: server
    tier: backend
