apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
data:
  config.yml: |
    admin:
      ip: 0.0.0.0
      port: 9990
    
    telemetry:
    - kind: io.l5d.prometheus
    - kind: io.l5d.recentRequests
      sampleRate: 0.25
    
    routers:
    - protocol: http
      label: outgoing
      interpreter:
        kind: io.l5d.namerd
        # dst: /$/inet/namerd.default.svc.cluster.local/4100
        dst: /$/inet/namerd.namerd.svc.cluster.local/4100
        namespace: internal
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: linkerd # Since we are deploying linkerd to the default namespace
          port: incoming
          service: l5d
      servers:
      - port: 4140
        ip: 0.0.0.0
      service:
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX

    - protocol: http
      label: incoming
      interpreter:
        kind: io.l5d.namerd
        # dst: /$/inet/namerd.default.svc.cluster.local/4100
        dst: /$/inet/namerd.namerd.svc.cluster.local/4100
        namespace: internal
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4141
        ip: 0.0.0.0

    - protocol: http
      label: external
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.namerd.svc.cluster.local/4100
        namespace: external
      servers:
      - port: 4142
        ip: 0.0.0.0