apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
    - name: my-pod
      image: alextanhongpin/server:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: my-pod-port
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: my-service-port
      protocol: TCP
      port: 80 # Expose at port 80
      targetPort: my-pod-port # Target port 8080
