---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: MyApp
      track: stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: MyApp
        track: stable
    spec:
      containers:
        - name: server
          image: alextanhongpin/server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['track']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: MyApp
      track: canary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: MyApp
        track: canary
    spec:
      containers:
        - name: server
          image: alextanhongpin/server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['track']
