apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  selector:
    matchLabels: 
      app: grpc-client
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: alextanhongpin/node-grpc-base-client
        imagePullPolicy: IfNotPresent
        env:
        - name: HOST_IP
          # curl localhost:8080/api/v1/namespaces/default/pods/l5d-h8t8z | grep hostIP
          # value: 192.168.99.100:4140
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PORT
          value: $(HOST_IP):4140