apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
  # namespace: l5d-system
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990
    
    namers:
    - kind: io.l5d.k8s

    routers:
    - protocol: http
      identifier:
        kind: io.l5d.ingress
        # host: localhost
        # port: 8001
      servers:
      - port: 80
        ip: 0.0.0.0
        clearContext: true
      dtab: |
        /svc => /#/io.l5d.k8s;
        # /host => /default/http;
        # /srv=>/#/io.l5d.k8s/default/http;
        # /host       => /srv;
        # /svc        => /host;
---