apiVersion: apps/v1
kind: Deployment
metadata:
        name: http-client
spec:
        selector:
                matchLabels:
                        run: http-client
        replicas: 1
        template:
                metadata:
                        labels:
                                run: http-client
                spec:
                        containers:
                        - name: http-client
                          image: alextanhongpin/http
                          imagePullPolicy: IfNotPresent
                          command: ["./app", "-service_uri=http://http-server:8080/hello"]
                          ports:
                          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
        name: http-client
        labels:
                run: http-client
spec:
        ports:
        - port: 8080
          protocol: TCP
        selector:
          run: http-client
        # When deploying Kubernetes on Docker Desktop, we need to use the type NodePort in order to call the service.
        # We can call the service by simply calling localhost:<NODE_PORT_IP>
        # curl http://localhost:$(k get svc http-client -o=jsonpath='{.spec.ports[0].nodePort}')
        type: NodePort
